version: "3.7"

services:
  jobmanager:
    image: flink:1.19.3-scala_2.12-java17
    command: jobmanager
    environment:
      - JOB_MANAGER_RPC_ADDRESS=jobmanager
    ports:
      - "8081:8081"
    volumes:
      - ./docker/assets/flink-conf.yaml:/opt/flink/conf/flink-conf.yaml
      - /shared/flink/checkpoints:/opt/flink/checkpoints
      - /shared/flink/datasets/nyc-taxi:/opt/flink/data/nyc-taxi
    networks:
      - web_server_overlay
    deploy:
      placement:
        constraints:
          - node.role == manager  
      replicas: 1

  taskmanager:
    image: flink:1.19.3-scala_2.12-java17
    command: taskmanager
    environment:
      - JOB_MANAGER_RPC_ADDRESS=jobmanager
    volumes:
      - ./docker/assets/flink-conf.yaml:/opt/flink/conf/flink-conf.yaml
      - /shared/flink/checkpoints:/opt/flink/checkpoints
      - /shared/flink/datasets/nyc-taxi:/opt/flink/data/nyc-taxi
    networks:
      - web_server_overlay
    deploy:
      replicas: 4       # 4 个 taskmanager
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - node.role == worker  # taskmanager 分布到 4 个从节点

networks:
  web_server_overlay:
    external: true

